sudo: false

services:
  - 'docker'

language: java

jdk:
  - oraclejdk8

before_install:
  - './.travis/main.sh'

install: ./gradlew --version

script: 
  # Run integration level tests if successful export
  # a bnd.run.jar file to be used in the image 
  # that is built
  - './gradlew check'
  - './gradlew export'
  - 'make image'

after_success:
  - if [[ "$TRAVIS_BRANCH" == "travis-push-image" ]]; then
      if [[ "$TRAVIS_REPO_SLUG", "craig8/GOSS-GRIDAPPS-D" ]]; then
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
        make push-image ;
      fi      
    fi

# don't notify me when things fail
notifications:
  email: false
