sudo: false

services:
  - 'docker'

language: java

jdk:
  - oraclejdk8

before_install:
  - './.travis/main.sh'

install: ./gradlew --version

script: 
  # Run integration level tests if successful export
  # a bnd.run.jar file to be used in the image 
  # that is built
#  - './gradlew check'
  - './gradlew export'

deploy:
  provider: script
  script: bash .travis/deploy.sh
  on:
    branch: travis-push-image

# don't notify me when things fail
notifications:
  email: false
