sudo: false

services:
  - 'docker'

language: java

jdk:
  - oraclejdk8

before_install:
  - './.travis/main.sh'

install: ./gradlew --version

deploy:
  provider: script
  script: bash .travis/deploy.sh
  on:
    branch: travis-push-image

# don't notify me when things fail
notifications:
  email: false
